on:
  push:
    paths-ignore:
      - "ga-ignore-"
  pull_request:
    paths-ignore:
      - "ga-ignore-"

env:
  MIRROR_URL: "${{ github.action_path }}"
  EXECUTABLES: "libmy.a, libchained_list.c, a.out"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    name: Check coding style
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
      volumes:
        - "coding-style_volume:/volume_mount"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Coding style
        run: (check.sh $(pwd) $(pwd))

  check_program_compilation:
    runs-on: ubuntu-latest
    name: Check program compilation
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make
        run: make
        timeout-minutes: 2
      - name: Clean
        run: make clean
      - name: Executables
        run: |
          for file in {{ EXECUTABLES }}
          do
            if [ -f "$file" ]; then
                echo "$file exists."
            fi
          done
